name: Ruby CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} - Gemfile ${{ matrix.gemfile }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3]
        gemfile:
          - rails_7.0
          - rails_7.1
          - rails_7.2
          - rails_edge
    env:
      RAILS_ENV: test
      DISPLAY: ":99.0"

    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    - name: Set up PhantomJS
      run: |
        mkdir -p travis-phantomjs
        wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
        tar -xvf travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C travis-phantomjs
        echo "$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin" >> $GITHUB_PATH

    - name: Run tests
      run: bundle exec rspec
      env:
       BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
